title: Eson Paguia
email: hi@esonpaguia.com
description: > # this means to ignore newlines until "baseurl:"
  I am a web developer helping make the world a better place 
  through JavaScript, Java, Spring, and UI design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://esonpaguia.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: esonpaguia
github_username:  esonpaguia
email_address: hi@esonpaguia.com

# files
layouts: ./_/layouts
includes: ./_/includes
destination: ./_/site
sass:
  sass_dir: ./_/sass

# Markdown
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class


# Site settings
permalink: /:title.html
exclude: ["Makefile", "README.md", "Gemfile", "Gemfile.lock", "CNAME"]

# Site info
meta:
  title: Eson Paguia
  author: Eson Paguia
  name: Eson Paguia
  hostname: esonpaguia.com

facebook:
  app_id: 1685611901660551
  admin: esonpaguia

analytics:
  id: "UA-57991635-2"

defaults:
  - scope:
      path: ""
    values:
      layout: "landing"
      tags: []
